const ADMIN_LOGIN='2347',ADMIN_PASSWORD='2203',KEY='pvz_v2_history';let history=JSON.parse(localStorage.getItem(KEY)||'[]'),reader=null,lastCode='',lastTime=0;
const $=id=>document.getElementById(id);
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){if(!history.length){$('history').innerHTML='<p class="muted">История пока пустая</p>';return}$('history').innerHTML=history.map(x=>`<div class="item ${x.ok?'ok':'bad'}"><div><b>${esc(x.code)}</b><br><span class="small">${x.ok?'Успешно':'Ошибка'}</span></div><span class="small">${new Date(x.time).toLocaleString('ru-RU')}</span></div>`).join('')}
function save(){localStorage.setItem(KEY,JSON.stringify(history));render()}
let audio;
function beep(freq,dur,type='sine'){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.18,audio.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+dur+.02)}catch(e){}}
function success(){beep(880,.1);setTimeout(()=>beep(1175,.12),100)}function fail(){beep(220,.18,'square');setTimeout(()=>beep(160,.22,'square'),170)}
function valid(code){return code.length>0&&!/^(ERROR|UNKNOWN|INVALID)$/i.test(code)}
function process(raw){let code=String(raw||'').trim();if(!code)return;let ok=valid(code);$('status').textContent=(ok?'✓ Успешное сканирование: ':'✕ Неизвестный код: ')+code;$('status').className='status '+(ok?'ok':'bad');ok?success():fail();history.unshift({code,ok,time:Date.now()});history=history.slice(0,100);save();$('code').value='';$('code').focus()}
$('check').onclick=()=>process($('code').value);$('code').addEventListener('keydown',e=>{if(e.key==='Enter')process($('code').value)});
// USB 2D scanner: normally sends characters and Enter, like a keyboard.
document.addEventListener('keydown',e=>{if(document.activeElement!==$('code')&&!e.ctrlKey&&!e.altKey&&!e.metaKey&&(e.key.length===1||e.key==='Enter'))$('code').focus()});
$('camera').onclick=async()=>{if(typeof Html5Qrcode==='undefined'){fail();$('status').textContent='Модуль камеры не загрузился';$('status').className='status bad';return}$('reader').classList.remove('hidden');$('camera').classList.add('hidden');$('stop').classList.remove('hidden');reader=new Html5Qrcode('reader');try{await reader.start({facingMode:'environment'},{fps:10,qrbox:{width:250,height:250}},text=>{let now=Date.now();if(text===lastCode&&now-lastTime<1500)return;lastCode=text;lastTime=now;process(text)},()=>{})}catch(e){$('status').textContent='Камера недоступна. Разрешите доступ к камере. Для телефона используйте HTTPS.';$('status').className='status bad';fail();stopCamera()}};
$('stop').onclick=stopCamera;async function stopCamera(){if(reader){try{await reader.stop()}catch(e){}try{reader.clear()}catch(e){}reader=null}$('reader').classList.add('hidden');$('camera').classList.remove('hidden');$('stop').classList.add('hidden')}
$('clear').onclick=()=>{if(confirm('Очистить историю?')){history=[];save()}};
$('adminOpen').onclick=()=>{$('loginModal').classList.remove('hidden');$('login').focus()};$('loginClose').onclick=()=>$('loginModal').classList.add('hidden');$('adminClose').onclick=()=>$('adminModal').classList.add('hidden');
$('loginBtn').onclick=()=>{if($('login').value===ADMIN_LOGIN&&$('pass').value===ADMIN_PASSWORD){$('loginModal').classList.add('hidden');$('adminModal').classList.remove('hidden');stats();$('loginErr').textContent=''}else{$('loginErr').textContent='Неверный логин или пароль';fail()}};$('pass').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginBtn').click()});$('logout').onclick=()=>$('adminModal').classList.add('hidden');
function stats(){let ok=history.filter(x=>x.ok).length; $('stats').innerHTML=`<div class="statgrid"><div class="stat">Всего<b>${history.length}</b></div><div class="stat">Успешных<b>${ok}</b></div><div class="stat">Ошибок<b>${history.length-ok}</b></div><div class="stat">Последнее<b>${history[0]?new Date(history[0].time).toLocaleTimeString('ru-RU'):'—'}</b></div></div>`}
render();
